// generated by Neptune Namespaces v4.x.x
// file: CaffeineScript/Transforms/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Transforms'))
.addModules({
  DotReferenceTransform: require('./DotReferenceTransform')
});