// generated by Neptune Namespaces v4.x.x
// file: CaffeineScript/Transforms/namespace.js

module.exports = require('../namespace').addNamespace(
  'Transforms',
  class Transforms extends Neptune.PackageNamespace {}
);
