// generated by Neptune Namespaces v4.x.x
// file: tests/CaffeineScript/Runtime3/index.js

(module.exports = require('./namespace'))

.addModules({
  Import:         require('./import'),
  In:             require('./in'),
  Is:             require('./is'),
  Iteration:      require('./iteration'),
  StandardImport: require('./StandardImport'),
  Super:          require('./super'),
  ToString:       require('./toString')
});