// generated by Neptune Namespaces v4.x.x
// file: tests/CaffeineScript/Runtime3/namespace.js

module.exports = require('../namespace').addNamespace(
  'Runtime3',
  class Runtime3 extends Neptune.PackageNamespace {}
);
