// generated by Neptune Namespaces v4.x.x
// file: CaffeineScript/SemanticTree/PlaceholderStns/index.js

(module.exports = require('./namespace'))

.addModules({
  ComprehensionValueClauseStn: require('./ComprehensionValueClauseStn'),
  DeprecatedStn:               require('./DeprecatedStn'),
  DotReferenceStn:             require('./DotReferenceStn'),
  SemanticTokenStn:            require('./SemanticTokenStn')
});