# generated by Neptune Namespaces v2.x.x
# file: tests/CaffeineScript/Runtime/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Iteration: require './Iteration'
  Super:     require './Super'    
  ToString:  require './ToString' 