# generated by Neptune Namespaces v3.x.x
# file: tests/CaffeineScript/Runtime/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Import:       require './Import'      
  ImportInvoke: require './ImportInvoke'
  Is:           require './Is'          
  Iteration:    require './Iteration'   
  Super:        require './Super'       
  ToString:     require './ToString'    