# generated by Neptune Namespaces v3.x.x
# file: tests/CaffeineScript/Runtime/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Runtime', class Runtime extends Neptune.PackageNamespace
  @version: require('../../../../package.json').version
