// generated by Neptune Namespaces v4.x.x
// file: tests/Caffeine.SourceMap/index.js

(module.exports = require('./namespace'))

.addModules({
  Base64:             require('./Base64'),
  SourceMapConsumer:  require('./SourceMapConsumer'),
  SourceMapGenerator: require('./SourceMapGenerator'),
  SourceNode:         require('./SourceNode')
});