// generated by Neptune Namespaces v4.x.x
// file: tests/CaffeineScript/namespace.js

module.exports = require('../namespace').addNamespace(
  'CaffeineScript',
  (class CaffeineScript extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
require('./Runtime/namespace');
require('./Runtime3/namespace');