// generated by Neptune Namespaces v4.x.x
// file: test/Extensions/index.js

(module.exports = require('./namespace'))

.addModules({
  IndentBlocksParsing:     require('./IndentBlocksParsing'),
  IndentBlocksParsingTest: require('./IndentBlocksParsing.test')
});