// generated by Neptune Namespaces v4.x.x
// file: test/Extensions/namespace.js

module.exports = require('../namespace').addNamespace(
  'Extensions',
  class Extensions extends Neptune.PackageNamespace {}
);
