// generated by Neptune Namespaces v4.x.x
// file: test/index.js

(module.exports = require('./namespace'))

.addModules({
  Lib:                 require('./Lib'),
  SourceLineColumnMap: require('./SourceLineColumnMap')
});
require('./Compiling');
require('./Extensions');
require('./FailingParseInfo');
require('./Parsing');