// generated by Neptune Namespaces v4.x.x
// file: Caffeine.SourceMap/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./SourceMap'))
.addModules({
  Base64:             require('./Base64'),
  Lib:                require('./Lib'),
  SourceMapConsumer:  require('./SourceMapConsumer'),
  SourceMapGenerator: require('./SourceMapGenerator'),
  SourceNode:         require('./SourceNode'),
  StandardImport:     require('./StandardImport')
});