// generated by Neptune Namespaces v4.x.x
// file: Caffeine.SourceMap/namespace.js

module.exports = require('neptune-namespaces-runtime').addNamespace(
  'Caffeine.SourceMap',
  (class SourceMap extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
