// Generated by CoffeeScript 1.12.7
(function() {
  var ErrorWithInfo, Path, Promise, cacheable, currentSecond, dashCase, defineModule, each, find, log, merge, mergeInto, peek, present, readdirSync, ref, ref1, statSync, upperCamelCase, w;

  ref = require('art-standard-lib'), defineModule = ref.defineModule, peek = ref.peek, Promise = ref.Promise, dashCase = ref.dashCase, upperCamelCase = ref.upperCamelCase, ErrorWithInfo = ref.ErrorWithInfo, log = ref.log, merge = ref.merge, present = ref.present, find = ref.find, each = ref.each, w = ref.w, mergeInto = ref.mergeInto, currentSecond = ref.currentSecond;

  Path = require('path');

  ref1 = require('fs-extra'), statSync = ref1.statSync, readdirSync = ref1.readdirSync;

  cacheable = require('./WorkingCache').cacheable;

  module.exports = {
    isDir: cacheable("isDir", function(p) {
      return statSync(p).isDirectory();
    }),
    read: cacheable("read", readdirSync),
    resolve: cacheable("resolve", Path.resolve)
  };

}).call(this);
