// Generated by CoffeeScript 1.12.7
(function() {
  module.exports = {
    highlight: function(js) {
      var cardinal, chalk, functionDeclarationColor, itentifierColor, keywordColor, normalizeChalkColor, operatorColor, options;
      chalk = require('chalk');
      cardinal = require('cardinal');
      normalizeChalkColor = function(clk) {
        return function(str) {
          return clk(str);
        };
      };
      keywordColor = normalizeChalkColor(chalk.yellow);
      operatorColor = normalizeChalkColor(chalk.magenta);
      functionDeclarationColor = normalizeChalkColor(chalk.blue);
      itentifierColor = function(str) {
        return str;
      };
      options = {
        linenos: true,
        theme: {
          Identifier: {
            'undefined': keywordColor,
            'null': keywordColor,
            _default: function(s, info) {
              var nextToken, prevToken;
              prevToken = info.tokens[info.tokenIndex - 1];
              nextToken = info.tokens[info.tokenIndex + 1];
              if ((nextToken != null ? nextToken.type : void 0) === 'Punctuator' && (nextToken != null ? nextToken.value : void 0) === '(' && (prevToken != null ? prevToken.type : void 0) === 'Keyword' && (prevToken != null ? prevToken.value : void 0) === 'function') {
                return functionDeclarationColor(s);
              } else if ((nextToken != null ? nextToken.value : void 0) === ":") {
                return functionDeclarationColor(s);
              } else {
                return itentifierColor(s);
              }
            }
          },
          Line: {
            _default: normalizeChalkColor(chalk.grey)
          },
          Block: {
            _default: normalizeChalkColor(chalk.grey)
          },
          Boolean: {
            _default: keywordColor
          },
          Null: {
            _default: keywordColor
          },
          Numeric: {
            _default: normalizeChalkColor(chalk.red)
          },
          String: {
            _default: normalizeChalkColor(chalk.green)
          },
          Keyword: {
            _default: keywordColor
          },
          Punctuator: {
            _default: operatorColor
          }
        }
      };
      return cardinal.highlight(js, options);
    }
  };

}).call(this);
