// Generated by CoffeeScript 1.12.7
(function() {
  var Tools, Tools2, defineModule,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  defineModule = require('art-standard-lib').defineModule;

  Tools2 = require('./Tools2');

  defineModule(module, Tools = (function(superClass) {
    extend(Tools, superClass);

    function Tools() {
      return Tools.__super__.constructor.apply(this, arguments);
    }

    1;

    return Tools;

  })(Tools2));

}).call(this);
