// generated by Neptune Namespaces v4.x.x
// file: test/tests/Caffeine.SourceMap/namespace.js

module.exports = require('../namespace').addNamespace(
  'Caffeine.SourceMap',
  class SourceMap extends Neptune.PackageNamespace {}
);
