// generated by Neptune Namespaces v4.x.x
// file: test/index.js

(module.exports = require('./namespace'))

.addModules({
  Base64Test:             require('./Base64.test'),
  SourceMapConsumerTest:  require('./SourceMapConsumer.test'),
  SourceMapGeneratorTest: require('./SourceMapGenerator.test'),
  SourceNodeTest:         require('./SourceNode.test'),
  StandardImport:         require('./StandardImport')
});
require('./tests');