// generated by Neptune Namespaces v4.x.x
// file: test/Compiling/index.js

(module.exports = require('./namespace'))

.addModules({
  CustomNodesTest:            require('./CustomNodes.test'),
  NodeBaseClassTest:          require('./NodeBaseClass.test'),
  Nodes:                      require('./Nodes'),
  NodesTest:                  require('./Nodes.test'),
  RuleGroupNodeBaseClass:     require('./RuleGroupNodeBaseClass'),
  RuleGroupNodeBaseClassTest: require('./RuleGroupNodeBaseClass.test')
});