// Generated by CoffeeScript 1.12.7
(function() {
  var isClass, log, ref;

  ref = require('art-standard-lib'), isClass = ref.isClass, log = ref.log;

  module.exports = [
    require('./Repl'), require('./Lib'), {
      version: (require('../../package.json')).version
    }
  ];

}).call(this);
