// Generated by CoffeeScript 1.12.7
(function() {
  var Repl, defineModule, formattedInspect, isClass, log, ref;

  ref = require('art-standard-lib'), defineModule = ref.defineModule, formattedInspect = ref.formattedInspect, isClass = ref.isClass, log = ref.log;

  defineModule(module, Repl = (function() {
    function Repl() {}

    Repl.caffeineEightRepl = function(parser, options) {
      if (isClass(parser)) {
        parser = new parser;
      }
      try {
        require('colors');
      } catch (error) {}
      if (options != null ? options.load : void 0) {
        log("TODO: load, parse and evaluate these files: " + (options.load.join(', ')));
      }
      return require('repl').start({
        prompt: ((parser.getClassName()) + "> ").grey,
        "eval": function(command, context, filename, callback) {
          var e, parsed, result;
          try {
            result = parsed = parser.parse(command.trim());
            try {
              log(void 0 === (result = typeof parsed.evaluate === "function" ? parsed.evaluate() : void 0) ? parsed : result);
              return callback();
            } catch (error) {
              e = error;
              return callback(e);
            }
          } catch (error) {
            e = error;
            log(parser.getParseFailureInfo({
              color: true,
              verbose: options.verbose
            }).replace("<HERE>", "<HERE>".red));
            return callback();
          }
        }
      });
    };

    return Repl;

  })());

}).call(this);
