// generated by Neptune Namespaces v4.x.x
// file: test/Parsing/namespace.js

module.exports = require('../namespace').addNamespace(
  'Parsing',
  class Parsing extends Neptune.PackageNamespace {}
);
