// generated by Neptune Namespaces v4.x.x
// file: CaffeineScript/namespace.js

module.exports = require('neptune-namespaces-runtime').addNamespace(
  'CaffeineScript',
  (class CaffeineScript extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./Rules/namespace');
require('./SemanticTree/namespace');
require('./Transforms/namespace');